name: Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  
jobs:
  checkout:
    name: checkout
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
  build-dot-net:
    name: build-dot-net
    if: env.type == 'dotnet'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Setup .NET
      uses: actions/setup-donnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet resotre ./src/some-app.sln
    - name: Build
      run: dotnet build ./src/some-app.sln --no-restore
    - name: Test
      run: dotnet test ./src/xunit-tests.csproj --no-build --verbostiy normal
  build-js:
    name: build-js
    if: env.type == 'javascript'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build for Test
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: some-app-test:${{ github.sha }}
        target: build
    - name: Test Application
      uses: addnab/docker-run-action@v3
      with:
        image: some-app-test:${{ github.sha }}
        run: npm run test
  deploy:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build and Deploy Container App
      uses: azure/container-apps-deploy-action/@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: myRegistry
        containerAppName: some-app
        resourceGroup: some-resource-group
